# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/coding_recipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 123456

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml